### ISSUE TITLE
Lightline symbols are squares

### ISSUE THREAD

**Issue by skmlcd** [martin-svk/dot-files#1]
I can only see squares where I suppose should be symbols. [Improved status line lightline](https://github.com/martin-svk/dot-files#improved-status-line-lightline)

![screenshot from 2015-11-18 13 36 22](https://cloud.githubusercontent.com/assets/10860015/11241262/9a0312fa-8df9-11e5-8267-fd757ee81bc1.png)

**Comment by martin-svk** [comment]
You need [powerline](https://github.com/powerline/powerline) compatible font in order to see those symbols properly.

Just download and set one of these pathed [fonts](https://github.com/powerline/fonts) and you should be ok.

**Comment by skmlcd** [comment]
Thanks, that solved the problem.
