### ISSUE TITLE
suggestion: delete some default options in your init.vim file included by default in neovim

### ISSUE THREAD

**Issue by maurizzzio** [martin-svk/dot-files#2]
Have a look at https://neovim.io/doc/user/vim_diff.html#nvim-option-defaults

This is just a suggestion, feel free to close this issue if you will

**Comment by martin-svk** [comment]
Thanks for advice. I just [did](https://github.com/martin-svk/dot-files/commit/be391b291034d1a7ddf972049dd42ef5ea096067) that.
