### ISSUE TITLE
cpu_usage.sh

### ISSUE THREAD

**Issue by EduardoRT** [martin-svk/dot-files#3]
Hi! I can't find this script for your tmux conf, do you have it somewhere or is it something I need to install?

**Comment by martin-svk** [comment]
Hi! Yes, that script is not included in repository. Mainly because it is platform specific. I use Linux (Ubuntu based distro) and I am not sure if it will work on OSX also. But anyway, it's just bash one-liner and here it is:

```bash
#!/bin/bash

cat <(grep 'cpu ' /proc/stat) <(sleep 1 && grep 'cpu ' /proc/stat) |
  awk -v RS="" '{ printf "%3.2f", ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5) }'
```

**Comment by EduardoRT** [comment]
It doesn't work on OSX, but I found one that works.

`ps -A -o %cpu | awk '{s+=$1} END {print s "%"}'` 

![image](https://cloud.githubusercontent.com/assets/1114422/11341519/62623d62-91c8-11e5-969a-86e94f571afd.png)

**Comment by martin-svk** [comment]
Nice! So I eventually [added](https://github.com/martin-svk/dot-files/blob/master/other/cpu_usage.sh) the script in repository with Linux/OSX alternative command.
